/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RemedyFinderRouteImport } from './routes/remedy-finder'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as BookRouteImport } from './routes/book'
import { Route as AgentPortalRouteImport } from './routes/agent-portal'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalShippingRouteImport } from './routes/legal.shipping'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AgentRespondRouteImport } from './routes/agent.respond'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicBookingsRespondRouteImport } from './routes/api.public.bookings.respond'
import { Route as ApiPublicBookingsCreateRouteImport } from './routes/api.public.bookings.create'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RemedyFinderRoute = RemedyFinderRouteImport.update({
  id: '/remedy-finder',
  path: '/remedy-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPortalRoute = AgentPortalRouteImport.update({
  id: '/agent-portal',
  path: '/agent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalShippingRoute = LegalShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => LegalRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRespondRoute = AgentRespondRouteImport.update({
  id: '/respond',
  path: '/respond',
  getParentRoute: () => AgentRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingsRespondRoute =
  ApiPublicBookingsRespondRouteImport.update({
    id: '/api/public/bookings/respond',
    path: '/api/public/bookings/respond',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingsCreateRoute = ApiPublicBookingsCreateRouteImport.update({
  id: '/api/public/bookings/create',
  path: '/api/public/bookings/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent-portal': typeof AgentPortalRoute
  '/book': typeof BookRoute
  '/consultation': typeof ConsultationRoute
  '/legal': typeof LegalRouteWithChildren
  '/remedy-finder': typeof RemedyFinderRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agent/respond': typeof AgentRespondRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/bookings/create': typeof ApiPublicBookingsCreateRoute
  '/api/public/bookings/respond': typeof ApiPublicBookingsRespondRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent-portal': typeof AgentPortalRoute
  '/book': typeof BookRoute
  '/consultation': typeof ConsultationRoute
  '/legal': typeof LegalRouteWithChildren
  '/remedy-finder': typeof RemedyFinderRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agent/respond': typeof AgentRespondRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/bookings/create': typeof ApiPublicBookingsCreateRoute
  '/api/public/bookings/respond': typeof ApiPublicBookingsRespondRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/agent-portal': typeof AgentPortalRoute
  '/book': typeof BookRoute
  '/consultation': typeof ConsultationRoute
  '/legal': typeof LegalRouteWithChildren
  '/remedy-finder': typeof RemedyFinderRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/agent/respond': typeof AgentRespondRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/$handle': typeof ProductHandleRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/bookings/create': typeof ApiPublicBookingsCreateRoute
  '/api/public/bookings/respond': typeof ApiPublicBookingsRespondRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/agent-portal'
    | '/book'
    | '/consultation'
    | '/legal'
    | '/remedy-finder'
    | '/shop'
    | '/sitemap.xml'
    | '/testimonials'
    | '/unsubscribe'
    | '/agent/respond'
    | '/email/unsubscribe'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/shipping'
    | '/legal/terms'
    | '/product/$handle'
    | '/lovable/email/suppression'
    | '/api/public/bookings/create'
    | '/api/public/bookings/respond'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/agent-portal'
    | '/book'
    | '/consultation'
    | '/legal'
    | '/remedy-finder'
    | '/shop'
    | '/sitemap.xml'
    | '/testimonials'
    | '/unsubscribe'
    | '/agent/respond'
    | '/email/unsubscribe'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/shipping'
    | '/legal/terms'
    | '/product/$handle'
    | '/lovable/email/suppression'
    | '/api/public/bookings/create'
    | '/api/public/bookings/respond'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/agent-portal'
    | '/book'
    | '/consultation'
    | '/legal'
    | '/remedy-finder'
    | '/shop'
    | '/sitemap.xml'
    | '/testimonials'
    | '/unsubscribe'
    | '/agent/respond'
    | '/email/unsubscribe'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/shipping'
    | '/legal/terms'
    | '/product/$handle'
    | '/lovable/email/suppression'
    | '/api/public/bookings/create'
    | '/api/public/bookings/respond'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  AgentPortalRoute: typeof AgentPortalRoute
  BookRoute: typeof BookRoute
  ConsultationRoute: typeof ConsultationRoute
  LegalRoute: typeof LegalRouteWithChildren
  RemedyFinderRoute: typeof RemedyFinderRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProductHandleRoute: typeof ProductHandleRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicBookingsCreateRoute: typeof ApiPublicBookingsCreateRoute
  ApiPublicBookingsRespondRoute: typeof ApiPublicBookingsRespondRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remedy-finder': {
      id: '/remedy-finder'
      path: '/remedy-finder'
      fullPath: '/remedy-finder'
      preLoaderRoute: typeof RemedyFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-portal': {
      id: '/agent-portal'
      path: '/agent-portal'
      fullPath: '/agent-portal'
      preLoaderRoute: typeof AgentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/shipping': {
      id: '/legal/shipping'
      path: '/shipping'
      fullPath: '/legal/shipping'
      preLoaderRoute: typeof LegalShippingRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof LegalRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/respond': {
      id: '/agent/respond'
      path: '/respond'
      fullPath: '/agent/respond'
      preLoaderRoute: typeof AgentRespondRouteImport
      parentRoute: typeof AgentRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/respond': {
      id: '/api/public/bookings/respond'
      path: '/api/public/bookings/respond'
      fullPath: '/api/public/bookings/respond'
      preLoaderRoute: typeof ApiPublicBookingsRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/create': {
      id: '/api/public/bookings/create'
      path: '/api/public/bookings/create'
      fullPath: '/api/public/bookings/create'
      preLoaderRoute: typeof ApiPublicBookingsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentRouteChildren {
  AgentRespondRoute: typeof AgentRespondRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentRespondRoute: AgentRespondRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface LegalRouteChildren {
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalShippingRoute: typeof LegalShippingRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalShippingRoute: LegalShippingRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  AgentPortalRoute: AgentPortalRoute,
  BookRoute: BookRoute,
  ConsultationRoute: ConsultationRoute,
  LegalRoute: LegalRouteWithChildren,
  RemedyFinderRoute: RemedyFinderRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProductHandleRoute: ProductHandleRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicBookingsCreateRoute: ApiPublicBookingsCreateRoute,
  ApiPublicBookingsRespondRoute: ApiPublicBookingsRespondRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
