/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RemedyFinderRouteImport } from './routes/remedy-finder'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AgentPortalRouteImport } from './routes/agent-portal'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RemedyFinderRoute = RemedyFinderRouteImport.update({
  id: '/remedy-finder',
  path: '/remedy-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPortalRoute = AgentPortalRouteImport.update({
  id: '/agent-portal',
  path: '/agent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-portal': typeof AgentPortalRoute
  '/consultation': typeof ConsultationRoute
  '/remedy-finder': typeof RemedyFinderRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/product/$handle': typeof ProductHandleRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-portal': typeof AgentPortalRoute
  '/consultation': typeof ConsultationRoute
  '/remedy-finder': typeof RemedyFinderRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/product/$handle': typeof ProductHandleRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/agent-portal': typeof AgentPortalRoute
  '/consultation': typeof ConsultationRoute
  '/remedy-finder': typeof RemedyFinderRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/product/$handle': typeof ProductHandleRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/agent-portal'
    | '/consultation'
    | '/remedy-finder'
    | '/shop'
    | '/testimonials'
    | '/email/unsubscribe'
    | '/product/$handle'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/agent-portal'
    | '/consultation'
    | '/remedy-finder'
    | '/shop'
    | '/testimonials'
    | '/email/unsubscribe'
    | '/product/$handle'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/agent-portal'
    | '/consultation'
    | '/remedy-finder'
    | '/shop'
    | '/testimonials'
    | '/email/unsubscribe'
    | '/product/$handle'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AgentPortalRoute: typeof AgentPortalRoute
  ConsultationRoute: typeof ConsultationRoute
  RemedyFinderRoute: typeof RemedyFinderRoute
  ShopRoute: typeof ShopRoute
  TestimonialsRoute: typeof TestimonialsRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProductHandleRoute: typeof ProductHandleRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remedy-finder': {
      id: '/remedy-finder'
      path: '/remedy-finder'
      fullPath: '/remedy-finder'
      preLoaderRoute: typeof RemedyFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-portal': {
      id: '/agent-portal'
      path: '/agent-portal'
      fullPath: '/agent-portal'
      preLoaderRoute: typeof AgentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AgentPortalRoute: AgentPortalRoute,
  ConsultationRoute: ConsultationRoute,
  RemedyFinderRoute: RemedyFinderRoute,
  ShopRoute: ShopRoute,
  TestimonialsRoute: TestimonialsRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProductHandleRoute: ProductHandleRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
